name: Build & Publish

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: "https://registry.npmjs.org"
      - uses: open-inc/github-action-npm-login@v1
        env:
          NPM_REGISTRY: ${{secrets.OPENINC_NPM_REGISTRY }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_ORG_OPENINC  }}
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Bump versions & push
        if: github.event_name == 'push'
        run: |
          git config --global user.name 'Automated publish'
          git config --global user.email 'stein@openinc.de'

          # Bump the patch version of every workspace package, then commit:
          for pkg in packages/*; do
            (cd "$pkg" && npm version patch --no-git-tag-version)
          done
          git commit -am "chore: bump package versions [skip ci]"
          git push

      - name: Build
        run: pnpm -r run build
      - name: Publish
        if: github.event_name == 'push'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_ORG_OPENINC  }}
        run: pnpm -r publish --access public --no-git-checks
